service: prototype-next-js

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: dev
  region: eu-west-2
  environment: 
    REDIRECT_URL: https://wq2djqdgc3.execute-api.eu-west-2.amazonaws.com/dev
    CLIENT_ID: 7tmk95dur3gjqklinuvevgahl9

plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    customHandler: ./config/custom.js
    assetsBucketName: assets.tdr.tna
    staticDir: ./assets
    routes:
      - src: ./assets/robots.txt
        path: robots.txt
      - src: ./assets/images/govuk-logotype-crown.png
        path: govuk-logotype-crown.png
      - src: ./assets/gov.css
        path: gov.css
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true
