service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: dev
  region: eu-west-2
  environment: 
    REDIRECT_URL: https://9ofer4y2x6.execute-api.eu-west-2.amazonaws.com/dev/
    CLIENT_ID: 7tmk95dur3gjqklinuvevgahl9

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    customHandler: ./config/custom.js
    assetsBucketName: assets.tdr.tna.com
    staticDir: ./assets
    routes:
      - src: ./assets/robots.txt
        path: robots.txt
      - src: ./assets/images/govuk-logotype-crown.png
        path: govuk-logotype-crown.png
      - src: ./assets/gov.css
        path: gov.css
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
